### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by rosspbarnes** [yoichiro/chromeos-filesystem-sftp#100]
I am trying to connect to my Arch linux system. This used to work in the past, but doesn't now. SSH/SFTP is installed and working with other apps on my chromebook. All I get is Server disconnected. I tried to follow your instructions to get the console log at https://github.com/yoichiro/chromeos-filesystem-sftp/wiki/How-to-Capture-the-Console-Log-of-DevTools. However, there is no option for background page. I have purchased this software and would like help so I can use it.

**Comment by yoichiro** [comment]
@rosspbarnes Did you purchase this software? This app is free...

**Comment by rosspbarnes** [comment]
Yes I did.

Order date: *September 3, 2014 7:08 AM*
  Google order number: *10370910874874185126.18055101478624783333*

**Comment by rosspbarnes** [comment]
Wow, I just realized that this is the app that does work. Sorry.
