### ISSUE TITLE
ChromeOS 63 screws up connect UI

### ISSUE THREAD

**Issue by triune** [yoichiro/chromeos-filesystem-sftp#121]
See screenshot. This began with ChromeOS 63 Beta...
...63 going to stable in 3-4 weeks! @yoichiro 

![screenshot 2017-11-06 at 11](https://user-images.githubusercontent.com/59974/32453596-3fd5a5f2-c2e2-11e7-9c56-85f848e35dcb.png)

**Comment by chopsticks-com** [comment]
Agreed.  Same problem.
