### ISSUE TITLE
Unable to remount after a failure.

### ISSUE THREAD

**Issue by mtomasz-chromium** [yoichiro/chromeos-filesystem-sftp#26]
1. Launch SFTP app.
2. Enter host, login, password.
3. Choose 'keyboard-interactive'.
4. Mount.
5. Fails with a message that keyboard-interactive password is not supported.
6. Change to 'password'
7. Hit Mount again.
8. Fails with a message 'Already mounted: sftpfs://...'

Expected:
Successfully mounted.

Actual:
Can't remount. It says it's mounted, but it's not mounted in Files app.

Workaround:
Disable and re-enable the extension in chrome://extensions.

**Comment by yoichiro** [comment]
@mtomasz-chromium I heard this same issue from other friend. I try to this fix.

**Comment by yoichiro** [comment]
https://github.com/yoichiro/chromeos-filesystem-sftp/pull/29

**Comment by yoichiro** [comment]
This issue will be fixed at the next release.
