### ISSUE TITLE
UI issues.

### ISSUE THREAD

**Issue by mtomasz-chromium** [yoichiro/chromeos-filesystem-sftp#27]
These are small things, but very visible. The window looks good on the screenshot in the web store, but on my chromebook:

1. Top margin is much smaller than all other margins.
2. Left and right margins are too large (3 cm on my screen).

**Comment by yoichiro** [comment]
I intend to fix this issue at the same time of #24.

**Comment by yoichiro** [comment]
This will be supported at the next version: https://github.com/yoichiro/chromeos-filesystem-sftp/pull/30
