### ISSUE TITLE
Listing directories very slow.

### ISSUE THREAD

**Issue by mtomasz-chromium** [yoichiro/chromeos-filesystem-sftp#28]
For a directory with 20 files, it takes couple of minutes to list them. Listing a directory with 2 files only is not so much faster, it's also at least a minute.

**Comment by yoichiro** [comment]
This implementation executes "connecting, handshaking, concrete request sending and closing" against each API calling. Therefore, if the handshaking takes a long time, the response will become too late...

**Comment by mtomasz-chromium** [comment]
Can we reuse connections?

**Comment by yoichiro** [comment]
@mtomasz-chromium I just merged some diff to the master branch to fix this issue. Until now, "connection, handshake, send request, close" steps were executed for each API calling. Instead, the next version uses one connection to access to all APIs. However, all API callings will be executed as serial. I expect that the performance of the next version will be increaded. #31

**Comment by yoichiro** [comment]
@mtomasz-chromium Probably, this issue will be fixed at same time as #41.

**Comment by yoichiro** [comment]
@mtomasz-chromium I close this issue because the cache layer has already been released.
