### ISSUE TITLE
Connection times out

### ISSUE THREAD

**Issue by andmalc** [yoichiro/chromeos-filesystem-sftp#36]
Connecting to standard OpenSSH server on Debian host on Google Compute Engine with a public key from Chromebook on Beta channel.

Initial connection is fast and filesystem is mounted.  However navigation is slow and I get repeated pop ups with message "Some operations are taking longer than expected" with option to click Abort.  Clicked on Abort but message continues to pop up.

**Comment by yoichiro** [comment]
@andmalc Hmm... When you access to the Debian server with the "sftp command" from your PC, is the performance good?

**Comment by andmalc** [comment]
Yes, performance is fine from my Linux machine using sshfs.  Also I often run interactive ssh sessions from my Chromebook and they usually run without any lag, though my Chromebook does sometimes briefly drop its wireless connection which I think was happening on and off while I was testing and causing navigation of the mounted server to be slow.  Navigation speed is OK now.

After more testing over different network connections and with different apps I find I consistently get the error is opening files with Chrome Dev Editor or the Zed Editor.   Uploading files from the mount to Drive or Dropbox is OK.

**Comment by andmalc** [comment]
More info: I have now tested on a 2nd Chromebook (running stable), with a 2nd server (my own laptop running Fedora), and again on a 2nd wireless network.  In all cases the mount displays the filesystem but the Chrome Dev Editor and the Zed Editor are unable to open the contents for editing, specifically: on the Chromebook on Stable the editors hang, and on the Chromebook on Beta, I get the Abort message I quoted above.  Also on the Beta Chromebook, Dev Editor sometimes shows this error:

    EncodingError: A URI supplied to the API was malformed, or the resulting Data URL has exceeded
    the URL length limitations for Data URLs.

**Comment by yoichiro** [comment]
@andmalc Hmm... I can't understand the detail situation. Could you confirm the outputs for this background context in the console of the DevTools? You can see the DevTools from the chrome://extensions page. I may know the cause from the outputs. If you face this issue at next time, please check the console output and let me know that here.

**Comment by andmalc** [comment]
Horaay!  Working fine in version 1.4.1

**Comment by yoichiro** [comment]
@andmalc Hmm... I can't understand why this issue was fixed, anyway, good result. :)
