### ISSUE TITLE
Save password into Profiles

### ISSUE THREAD

**Issue by friesoft** [yoichiro/chromeos-filesystem-sftp#39]
It would be nice if it would be possible to save passwords into profiles so I can just reconnect without entering my 40 char password each time..

**Comment by yoichiro** [comment]
@friesoft Thank you for the report. I intend to support to keep the credential including the password. But, for the security reason, the password will be kept when this storing feature turns on by the configuration settings. That is, the next version has an ability to open the configuration settings dialog on the left of bottom.

**Comment by yoichiro** [comment]
@friesoft I merged this diff: https://github.com/yoichiro/chromeos-filesystem-sftp/commit/9c48bc939285703b0b9fe069c6bc7488215ae469
