### ISSUE TITLE
Can't delete non-empty directories

### ISSUE THREAD

**Issue by DSteve595** [yoichiro/chromeos-filesystem-sftp#47]
Deleting folders that contain one or more files results in the Files manager spitting out "An error occurred. Some items may not have been deleted."
To delete the folder, I have to delete all files inside it. Then, the now-empty is able to be deleted.

P.S. Love the app! Props for being one of the first to use this API, and doing it really well.

**Comment by yoichiro** [comment]
@DSteve595 I understood and could reproduce this issue. I intend to fix this. Thank you for the report!

**Comment by yoichiro** [comment]
Just implemented. #49

**Comment by yoichiro** [comment]
@DSteve595 I have just released the new version 1.5.0 including supprting to delete a directory recursively. Close this issue. Thank you for the report!

**Comment by DSteve595** [comment]
Thanks so much!
