### ISSUE TITLE
treats folders with .com extensions as files

### ISSUE THREAD

**Issue by dackdotcom** [yoichiro/chromeos-filesystem-sftp#48]
This app looks awesome but I can't access any directory with the domain it's associated with (e.g. /pourcast.com) It thinks those are files when they're just directories.

**Comment by yoichiro** [comment]
@dackdotcom Hmm... I intend to investigate this issue. Probably, it will take a few days.

**Comment by yoichiro** [comment]
@dackdotcom Probably, the target directory may actually be a symbolic link, I guess. The current version of this app might not be treated corerctly...

**Comment by yoichiro** [comment]
I just released the new version 1.5.1, which the symbolic links are ignored.
