### ISSUE TITLE
Download triggering Intrusion Detection alert

### ISSUE THREAD

**Issue by itxpress** [yoichiro/chromeos-filesystem-sftp#54]
I realize this isn't something easy to handle and it's technically a false alert, but when trying to install your SFTP plugin, our company firewall blocked it due to an Intrusion Detection alert:

 2015-03-19 10:24:09 192.168.X.X:56422     31.13.69.160:80
     warn                idp                    ACCESS BLOCK
     Rule_id=11 [type=Sig(1058279)] WEB SQL injection attempt -14 Action: Reject Both Severity: high

Have never seen this when installing any Chrome extension before.

**Comment by yoichiro** [comment]
I don't have any reason... At least, I guess that this issue is the problem of Chrome WebStore. You can file this issue on crbug https://code.google.com/p/chromium/issues/list
