### ISSUE TITLE
Unable to open file with SFTP -31

### ISSUE THREAD

**Issue by folbricht** [yoichiro/chromeos-filesystem-sftp#60]
Client: Acer Chromebook 13 (ARM)
Server: freeSSHd 1.3.1 on Win7x64

I can logon to the server, browse directories, but all directories are empty. Running WinSCP as client locally does not have the same problem (it's not a file permissions issue).

![screenshot 2015-03-29 at 11 38 16 - copy](https://cloud.githubusercontent.com/assets/3505107/6886849/7288443c-d609-11e4-9ce6-c2318661ef5d.png)

**Comment by yoichiro** [comment]
@folbricht Is this error occurred every time? Or random?

**Comment by folbricht** [comment]
It's been occurring constantly, for at least a couple of weeks. I can see all the folders and go into those, but no files are shown anywhere.

Not 100% sure but I believe it worked when I set it up originally, right after it came out.

**Comment by yoichiro** [comment]
@folbricht I found some places where the close process was not correct, therefore, try to modify them.

**Comment by yoichiro** [comment]
@folbricht What did you fill in to the "Path as root directory"?

**Comment by folbricht** [comment]
I left it blank so far (was that field even there before?). Trying to test with that field populated but I think the latest version is broken. It crashes right away when trying to connect.
![screenshot 2015-04-04 at 09 43 43](https://cloud.githubusercontent.com/assets/3505107/6993368/2e005a66-daaf-11e4-952e-09c978e5eb0c.png)

![screenshot 2015-04-04 at 09 38 32-edit](https://cloud.githubusercontent.com/assets/3505107/6993362/f43e27e0-daae-11e4-90c4-7478878cd876.png)

**Comment by folbricht** [comment]
@yoichiro Thanks a lot for fixing the crash on ARM. But I still need your help getting it to work with freeSSHd on Windows. I can now mount successfully, but not browse any directories. Regardless what I put into `Path as root directory`, I get:

![screenshot 2015-04-26 at 09 33 16](https://cloud.githubusercontent.com/assets/3505107/7337895/600bd68a-ebf7-11e4-8f34-c1af21c89c7d.png)

The directory is shared as `M:\` in freeSSHd

![freesshd_settings](https://cloud.githubusercontent.com/assets/3505107/7337904/87ed02aa-ebf7-11e4-8d0b-39f55a14ed04.png)

But regardless what I try it always causes this error:
![screenshot 2015-04-26 at 09 29 00 - copy](https://cloud.githubusercontent.com/assets/3505107/7337901/7be10be6-ebf7-11e4-9849-95850121eee5.png)

I also tried other obvious ways of specifying the root path like `/`, `M:/`, `\` or leave it blank. None of that makes any difference. Do you have an example of what to put into `Path as root directory` when using a  Windows SSH server?

**Comment by folbricht** [comment]
Nevermind, that error above was my mistake.

I'm basically back to being able to mount ok, but not see any files even though I can see and browse all  directories. At this point I'll just have to give up on freeSSHd and try something else.

**Comment by folbricht** [comment]
Closing this since it works fine with other SFTP servers, just not with freeSSHd

**Comment by Z01DTech** [comment]
I was getting this same error while trying to connect to my webhosting's FTP server through Explicit FTPS.

On most FTP programs all I have to set for the directory is "/public_html/". With or without the ending slash, it doesn't usually seem to matter.

How I got it to work was by using the full path to the public_html folder WITHOUT a trailing slash. If I put a trailing slash, the error comes back

Full Path Example: /home/user321/public_html
