### ISSUE TITLE
Remember fingerprints for saved connections

### ISSUE THREAD

**Issue by gsf** [yoichiro/chromeos-filesystem-sftp#61]
If the fingerprint hasn't changed since the last login on a saved connection, I shouldn't be prompted to accept it again.

**Comment by yoichiro** [comment]
Just implemented: #62

**Comment by yoichiro** [comment]
@gsf Just released the new version 1.7.0 including this issue.Thank you for this report!

**Comment by gsf** [comment]
Wow, works just as expected. Thanks!

**Comment by yoichiro** [comment]
@gsf It's my pleasure.
