### ISSUE TITLE
WDMYCLOUD can't connect

### ISSUE THREAD

**Issue by MarkLants** [yoichiro/chromeos-filesystem-sftp#64]
After setting up a connection to my WDMYCLOUD and clicking Mount button I get "hostent is null 0".

**Comment by yoichiro** [comment]
@MarkLants This message means that the hostname you filled in was not resolved by DNS. That is, the server's IP address could not retrieved. Did you fill in the correct server name? Also, can the server name be registered into the DNS?

**Comment by MarkLants** [comment]
I get the same result with using the IP address.   No the local NAS device
is not defined to DNS

**Comment by yoichiro** [comment]
@MarkLants What did you fill in to the "ServerName/IP address" field? And, could you send the Console Log using the way described below?

https://github.com/yoichiro/chromeos-filesystem-sftp/wiki/How-to-Capture-the-Console-Log-of-DevTools

**Comment by yoichiro** [comment]
I close this issue, because I could not get enough information to fix this issue.
