### ISSUE TITLE
Copy hangs on git repos

### ISSUE THREAD

**Issue by gsf** [yoichiro/chromeos-filesystem-sftp#65]
When copying from a remote machine to local, if the directory has a `.git` subdirectory it hangs on copy. Eventually, I get a notification that the copy operation failed.

![screenshot 2015-04-02 at 10 59 13](https://cloud.githubusercontent.com/assets/151913/6966473/560989b2-d927-11e4-8c3b-0b12dceba93d.png)

**Comment by yoichiro** [comment]
@gsf Thank you for the reporting. Hmm... After occuring the error, was the sftp remote directory unmounted? It seems that the capture image has only two directories: Google Drive and Downloads...

**Comment by gsf** [comment]
Sorry, the screenshot could have been clearer. The remote directory is not unmounted by the error. See the shots below for the sequence of error messages I receive -- I continue to get the `SFTP-9 11` notifications with no progress in the copy until I unmount the remote directory. Note also that this the directory I am copying only has a few files in it so its size should not be a factor.

![screenshot 2015-04-04 at 16 03 23](https://cloud.githubusercontent.com/assets/151913/6994360/98824e1e-dae4-11e4-9eaa-df0d0c9ffebf.png)
![screenshot 2015-04-04 at 16 04 20](https://cloud.githubusercontent.com/assets/151913/6994362/9effbe20-dae4-11e4-82f6-ccf2919b1c11.png)
![screenshot 2015-04-04 at 16 05 18](https://cloud.githubusercontent.com/assets/151913/6994363/a3d6bffc-dae4-11e4-8f30-f0ff7d211eef.png)

**Comment by gsf** [comment]
And just as I left that comment, this time it eventually unmounted itself.

**Comment by gsf** [comment]
Now it either responds with an error or crashes NaCl and unmounts with each attempt. Screenshots with output in background context: 

![screenshot 2015-04-04 at 16 25 05](https://cloud.githubusercontent.com/assets/151913/6994415/42acffe0-dae7-11e4-8d09-20562daa684b.png)

![screenshot 2015-04-04 at 16 27 48](https://cloud.githubusercontent.com/assets/151913/6994439/c678fbee-dae7-11e4-99de-0b8a65ea2225.png)

**Comment by yoichiro** [comment]
@gsf Thanks a lot. I intend to check the code... Probably, it will be necessary a few weeks until finding the cause...

**Comment by gsf** [comment]
You've probably already guessed as much but it looks like the large number of directories for git objects is tripping up sftpfs.

**Comment by yoichiro** [comment]
@gsf In the latest version 1.7.3, the way of fetching the metadata for each file was changed from sync to async. Probably, I guess that the previous way (sync) was heavy logic against memory... Do you have some error continuously using the 1.7.3?

**Comment by gsf** [comment]
Directory copied successfully! Note that on larger, or even medium-sized projects the copy is taking a long time (~10 minutes), but that's a more general performance issue. This one looks to be fixed. Thanks!

**Comment by yoichiro** [comment]
@gsf It's a good news. Thank you for the reporting! Feel free to let me know if you find other issue.
