### ISSUE TITLE
Error when starting up SSH session -13 11

### ISSUE THREAD

**Issue by steveallen1987** [yoichiro/chromeos-filesystem-sftp#67]
Hi
![sftp error](https://cloud.githubusercontent.com/assets/11808534/6997794/0de7163e-dbc2-11e4-98e0-8830a836cdef.png)

I have just installed the SFTP file system app on ChromeOS (Toshiba Chromebook 2) and can not get it to connect.

I receive the errors in the attached screenshot.

Any advise?

Thanks,

**Comment by yoichiro** [comment]
@steveallen1987 The error code means that the socket was disconnected. Is the server supporting SSH2?

**Comment by steveallen1987** [comment]
Turns out the server I'm connecting to does not support SSH.

Thanks for your help.

**Comment by Numailia** [comment]
Why does the server need to support SSH2? Can't you just connect over FTP?
