### ISSUE TITLE
Unmount?

### ISSUE THREAD

**Issue by jksdua** [yoichiro/chromeos-filesystem-sftp#70]
Is there any way to unmount a drive to a server that is no longer accessible?

Current Behaviour:

- Notification that the server is taking too long to respond. Clicking abort allows the Files app to load.
- No close button to remove the drive
- Clicking eject has non effect

Expected Behaviour:

- Clicking eject or the close button should remove it from the Files app

**Comment by mtomasz-chromium** [comment]
This is a good idea. I'll consider implementing it.

**Comment by djaychela** [comment]
I'll second this - I have an issue which appears when I'm at home - my router doesn't allow my externally-routed OpenDNS name to be seen internally, so when I'm at home my server doesn't work, and I get constant "Too long to respond" messages, and the eject button (in the notifications or in the files app) doesn't work.

**Comment by yoichiro** [comment]
I close this issue, because the Files.app UI has already been changed.
