### ISSUE TITLE
Unable to init SFTP session -21 11

### ISSUE THREAD

**Issue by bthomson** [yoichiro/chromeos-filesystem-sftp#72]
Thank you for chromeos-filesystem-sftp, it is very nice!

When I press "MOUNT", and then "ACCEPT", error is: Unable to init SFTP session -21 11

**Comment by bthomson** [comment]
Found the issue: missing line in sshd_config for "Subsystem sftp".

**Comment by klarsen73** [comment]
Hi, 
Could you elaborate on what you did to make it work? I am getting the same error.

Thanks:)

**Comment by bthomson** [comment]
I added the following line to the sshd_config file on the server:

    Subsystem sftp /libexec/sftp-server

You probably have to adjust it to the actual path of the sftp-server binary on your system.
